services:
  main-db:
    image: postgres
    ports:
      - "5433:5432" # Порт должен быть строкой и иметь пробел после "-"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - main-db:/var/lib/postgres/data # Пробел после "-"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP-протокол (для подключения к RabbitMQ)
      - "15672:15672" # Web UI для управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  main-db: # Объявление тома на верхнем уровне
